---
title: "El junco de los páramos (Junco Vulcani)"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r carga-paquetes, message=FALSE, warning=FALSE}
# Carga de paquetes
library(dplyr)
library(sf)
library(DT)
library(plotly)
library(leaflet)
library(flexdashboard)
```

```{r carga-datos}
# Registros de presencia de Junco vulcani
junco_vulcani <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/junco_vulcani-cr-registros.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )

# Asignación de CRS
st_crs(junco_vulcani) = 4326

# Capa geespacial de cantones
cantones <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_cantones_simp_wgs84.geojson",
    quiet = TRUE
  )
```

```{r cruce-cantones, message=FALSE}
# Cruce espacial con la tabla de cantones, para obtener el nombre del cantón
junco_vulcani <- 
  junco_vulcani %>%
  st_join(cantones["canton"])
```

Registros de presencia, estacionalidad e historial
=======================================================================

Row {data-height=100}
-----------------------------------------------------------------------

### Registros de presencia {.value-box}
```{r}
valueBox(value = nrow(junco_vulcani), 
         caption = "Registros de presencia", 
         icon = "fas fa-crow", 
         color = "blue"
)
```

row {data-heigth=550}
-----------------------------------------------------------------------

### Registros de presencia

```{r tabla-registros}
# Tabla de registros de presencia
junco_vulcani %>%
  st_drop_geometry() %>%
  select(stateProvince, canton, locality, eventDate) %>%
  datatable(
    colnames = c("Provincia", "Cantón", "Localidad", "Fecha"),
    options = list(searchHighlight = TRUE)
  )
```

row {data-heigth=350}
-----------------------------------------------------------------------

### Gráfico de Estacionalidad

```{r grafico-estacionalidad}
# Gráfico de estacionalidad
junco_vulcani %>%
  st_drop_geometry() %>%
  group_by(mes = format(as.Date(eventDate, "%Y-%m-%d"), "%m")) %>%
  summarize(suma_registros = n()) %>%
  filter(!is.na(mes))  %>%
  plot_ly(x = ~ mes,
          y = ~ suma_registros,
          type="scatter", mode="markers", fill = "tozeroy", fillcolor = "green") %>%
  layout(title = "Estacionalidad",
         xaxis = list(title = "Mes"),
         yaxis = list(title = "Cantidad de registros"))
```

### Gráfico de Historial

```{r grafico-historial, warning=FALSE}
junco_vulcani %>%
  st_drop_geometry() %>%
  group_by(anio = format(as.Date(eventDate, "%Y-%m-%d"), "%Y")) %>%
  summarize(suma_registros = n()) %>%
  filter(!is.na(anio))  %>%
  filter(anio >= 2011) %>%
  plot_ly(x = ~ anio,
          y = ~ suma_registros,
          type="bar", color = "green") %>%
  layout(title = "Historial",
         xaxis = list(title = "Año"),
         yaxis = list(title = "Cantidad de registros"))
```

Mapa de distribución
=======================================================================

row
-----------------------------------------------------------------------

```{r mapa-distribucion}
# Mapa de registros de presencia
junco_vulcani %>%
  select(stateProvince,
         canton,
         locality,
         eventDate,
         decimalLongitude,
         decimalLatitude) %>%
  leaflet() %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addCircleMarkers(
    stroke = F,
    radius = 4,
    fillColor = 'red',
    fillOpacity = 1,
    popup = paste(
      junco_vulcani$stateProvince,
      junco_vulcani$canton,
      junco_vulcani$locality,
      junco_vulcani$eventDate,
      junco_vulcani$decimalLongitude,
      junco_vulcani$decimalLatitude,
      sep = '<br/>'
    ),
    group = "Junco vulcani"
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "Imágenes de ESRI"),
    overlayGroups = c("Junco vulcani")
  ) %>%
  addMiniMap(
    tiles = providers$Stamen.OpenStreetMap.Mapnik,
    position = "bottomleft",
    toggleDisplay = TRUE
  )
```











